[package]
name = "tiktoken"
version = "0.1.0"
edition = "2021"
keywords = ["tiktoken", "php", "extension"]

[lib]
crate-type = ["cdylib"]

[dependencies]
ext-php-rs = { version = "0.11", features = ["anyhow"] }
tiktoken-rs = "0.5"

[profile.release]
strip = "debuginfo"
